name: ntlm
description: Library for making HTTP requests that require NTLM authentication
version: 2.0.1
homepage: https://github.com/mrbbot/ntlm

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  http: ^1.0.0
  pointycastle: ^3.0.1
  fixnum: ^1.0.0